// Package pluginapi defines lomax's plugin protocol: the gRPC service
// contract subprocess plugins implement, hosted over HashiCorp go-plugin
// (see docs/music-cli-plan.md section 9).
//
// This file is the versioned wire contract. lomax guarantees backward
// compatibility within a major protocol version (see the handshake's
// ProtocolVersion in internal/pluginapi/handshake.go, which is independent
// of this schema's own evolution — adding fields here is safe under normal
// protobuf compatibility rules; ProtocolVersion only needs bumping for a
// breaking change).
//
// Milestone 5 implements exactly one hook as a real gRPC service:
// MetadataResolver, corresponding to the `resolve_metadata` hook in the
// plan's hook table. The other planned hooks (pre_import, post_import,
// pre_write_tags, post_write_tags, format_path, sync_device,
// pre_sync_transform, register_commands) are named there but not yet
// backed by a service definition — they'll get one as core grows a call
// site for them, rather than speculatively generating unused RPC surface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: internal/pluginapi/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        string                 `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMetadataRequest) Reset() {
	*x = ResolveMetadataRequest{}
	mi := &file_internal_pluginapi_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMetadataRequest) ProtoMessage() {}

func (x *ResolveMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginapi_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMetadataRequest.ProtoReflect.Descriptor instead.
func (*ResolveMetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveMetadataRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *ResolveMetadataRequest) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *ResolveMetadataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ResolveMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matched is false when the plugin's source has nothing for this track —
	// a normal, expected outcome, not an RPC error.
	Matched       bool   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	AlbumArtist   string `protobuf:"bytes,4,opt,name=album_artist,json=albumArtist,proto3" json:"album_artist,omitempty"`
	Album         string `protobuf:"bytes,5,opt,name=album,proto3" json:"album,omitempty"`
	Year          int32  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMetadataResponse) Reset() {
	*x = ResolveMetadataResponse{}
	mi := &file_internal_pluginapi_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMetadataResponse) ProtoMessage() {}

func (x *ResolveMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginapi_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMetadataResponse.ProtoReflect.Descriptor instead.
func (*ResolveMetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_pluginapi_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveMetadataResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *ResolveMetadataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResolveMetadataResponse) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *ResolveMetadataResponse) GetAlbumArtist() string {
	if x != nil {
		return x.AlbumArtist
	}
	return ""
}

func (x *ResolveMetadataResponse) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *ResolveMetadataResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

var File_internal_pluginapi_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_pluginapi_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"%internal/pluginapi/proto/plugin.proto\x12\tpluginapi\"\\\n" +
	"\x16ResolveMetadataRequest\x12\x16\n" +
	"\x06artist\x18\x01 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x02 \x01(\tR\x05album\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"\xae\x01\n" +
	"\x17ResolveMetadataResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12!\n" +
	"\falbum_artist\x18\x04 \x01(\tR\valbumArtist\x12\x14\n" +
	"\x05album\x18\x05 \x01(\tR\x05album\x12\x12\n" +
	"\x04year\x18\x06 \x01(\x05R\x04year2l\n" +
	"\x10MetadataResolver\x12X\n" +
	"\x0fResolveMetadata\x12!.pluginapi.ResolveMetadataRequest\x1a\".pluginapi.ResolveMetadataResponseB5Z3github.com/ferro-dev/lomax/internal/pluginapi/protob\x06proto3"

var (
	file_internal_pluginapi_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_pluginapi_proto_plugin_proto_rawDescData []byte
)

func file_internal_pluginapi_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_pluginapi_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_pluginapi_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pluginapi_proto_plugin_proto_rawDesc), len(file_internal_pluginapi_proto_plugin_proto_rawDesc)))
	})
	return file_internal_pluginapi_proto_plugin_proto_rawDescData
}

var file_internal_pluginapi_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pluginapi_proto_plugin_proto_goTypes = []any{
	(*ResolveMetadataRequest)(nil),  // 0: pluginapi.ResolveMetadataRequest
	(*ResolveMetadataResponse)(nil), // 1: pluginapi.ResolveMetadataResponse
}
var file_internal_pluginapi_proto_plugin_proto_depIdxs = []int32{
	0, // 0: pluginapi.MetadataResolver.ResolveMetadata:input_type -> pluginapi.ResolveMetadataRequest
	1, // 1: pluginapi.MetadataResolver.ResolveMetadata:output_type -> pluginapi.ResolveMetadataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pluginapi_proto_plugin_proto_init() }
func file_internal_pluginapi_proto_plugin_proto_init() {
	if File_internal_pluginapi_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pluginapi_proto_plugin_proto_rawDesc), len(file_internal_pluginapi_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pluginapi_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_pluginapi_proto_plugin_proto_depIdxs,
		MessageInfos:      file_internal_pluginapi_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_pluginapi_proto_plugin_proto = out.File
	file_internal_pluginapi_proto_plugin_proto_goTypes = nil
	file_internal_pluginapi_proto_plugin_proto_depIdxs = nil
}
