// Package pluginapi defines lomax's plugin protocol: the gRPC service
// contract subprocess plugins implement, hosted over HashiCorp go-plugin
// (see docs/music-cli-plan.md section 9).
//
// This file is the versioned wire contract. lomax guarantees backward
// compatibility within a major protocol version (see the handshake's
// ProtocolVersion in internal/pluginapi/handshake.go, which is independent
// of this schema's own evolution — adding fields here is safe under normal
// protobuf compatibility rules; ProtocolVersion only needs bumping for a
// breaking change).
//
// Milestone 5 implements exactly one hook as a real gRPC service:
// MetadataResolver, corresponding to the `resolve_metadata` hook in the
// plan's hook table. The other planned hooks (pre_import, post_import,
// pre_write_tags, post_write_tags, format_path, sync_device,
// pre_sync_transform, register_commands) are named there but not yet
// backed by a service definition — they'll get one as core grows a call
// site for them, rather than speculatively generating unused RPC surface.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: internal/pluginapi/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataResolver_ResolveMetadata_FullMethodName = "/pluginapi.MetadataResolver/ResolveMetadata"
)

// MetadataResolverClient is the client API for MetadataResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataResolver is implemented by plugins that add a metadata source to
// the resolver's fallback chain (see docs/music-cli-plan.md section 6's
// resolution order: MusicBrainz -> AcoustID -> Discogs -> Last.fm). Core
// calls ResolveMetadata with whatever tags the track currently has; the
// plugin looks the track up against its own source and reports a match, if
// any.
type MetadataResolverClient interface {
	ResolveMetadata(ctx context.Context, in *ResolveMetadataRequest, opts ...grpc.CallOption) (*ResolveMetadataResponse, error)
}

type metadataResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataResolverClient(cc grpc.ClientConnInterface) MetadataResolverClient {
	return &metadataResolverClient{cc}
}

func (c *metadataResolverClient) ResolveMetadata(ctx context.Context, in *ResolveMetadataRequest, opts ...grpc.CallOption) (*ResolveMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveMetadataResponse)
	err := c.cc.Invoke(ctx, MetadataResolver_ResolveMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataResolverServer is the server API for MetadataResolver service.
// All implementations must embed UnimplementedMetadataResolverServer
// for forward compatibility.
//
// MetadataResolver is implemented by plugins that add a metadata source to
// the resolver's fallback chain (see docs/music-cli-plan.md section 6's
// resolution order: MusicBrainz -> AcoustID -> Discogs -> Last.fm). Core
// calls ResolveMetadata with whatever tags the track currently has; the
// plugin looks the track up against its own source and reports a match, if
// any.
type MetadataResolverServer interface {
	ResolveMetadata(context.Context, *ResolveMetadataRequest) (*ResolveMetadataResponse, error)
	mustEmbedUnimplementedMetadataResolverServer()
}

// UnimplementedMetadataResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataResolverServer struct{}

func (UnimplementedMetadataResolverServer) ResolveMetadata(context.Context, *ResolveMetadataRequest) (*ResolveMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveMetadata not implemented")
}
func (UnimplementedMetadataResolverServer) mustEmbedUnimplementedMetadataResolverServer() {}
func (UnimplementedMetadataResolverServer) testEmbeddedByValue()                          {}

// UnsafeMetadataResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataResolverServer will
// result in compilation errors.
type UnsafeMetadataResolverServer interface {
	mustEmbedUnimplementedMetadataResolverServer()
}

func RegisterMetadataResolverServer(s grpc.ServiceRegistrar, srv MetadataResolverServer) {
	// If the following call panics, it indicates UnimplementedMetadataResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataResolver_ServiceDesc, srv)
}

func _MetadataResolver_ResolveMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataResolverServer).ResolveMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataResolver_ResolveMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataResolverServer).ResolveMetadata(ctx, req.(*ResolveMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataResolver_ServiceDesc is the grpc.ServiceDesc for MetadataResolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataResolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluginapi.MetadataResolver",
	HandlerType: (*MetadataResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveMetadata",
			Handler:    _MetadataResolver_ResolveMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pluginapi/proto/plugin.proto",
}
