package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ferro-dev/lomax/internal/audio"
	"github.com/ferro-dev/lomax/internal/library"
	"github.com/ferro-dev/lomax/internal/naming"
	"github.com/ferro-dev/lomax/internal/resolve"
)

// newImportCmd builds `lomax import <source> --dest <library>`: the import
// workflow — resolve metadata for files outside the library, show the
// diff, write the resolved tags, and copy (or, with --move, move) each
// file into the library at a path generated by the naming template.
func newImportCmd() *cobra.Command {
	var dest string
	var namingTemplate string
	var acoustidKey string
	var dbPath string
	var dryRun bool
	var move bool

	cmd := &cobra.Command{
		Use:   "import <source>",
		Short: "Resolve metadata, write tags, and add files to your library",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if dest == "" {
				return fmt.Errorf("--dest is required")
			}
			if acoustidKey == "" {
				acoustidKey = os.Getenv(acoustIDAPIKeyEnv)
			}
			return runImport(cmd, args[0], dest, namingTemplate, acoustidKey, dbPath, dryRun, move)
		},
	}
	cmd.Flags().StringVar(&dest, "dest", "", "library root to import files into (required)")
	cmd.Flags().StringVar(&namingTemplate, "naming-template", naming.Default, "destination path template (see docs/music-cli-plan.md section 8)")
	cmd.Flags().StringVar(&acoustidKey, "acoustid-key", "", "AcoustID API key for fingerprint lookups (or set "+acoustIDAPIKeyEnv+")")
	addLibraryDBFlag(cmd, &dbPath)
	cmd.Flags().BoolVar(&dryRun, "dry-run", true, "preview proposed changes without writing or moving files")
	cmd.Flags().BoolVar(&move, "move", false, "move source files into the library instead of copying them (default: copy, leaving the source untouched)")
	return cmd
}

func runImport(cmd *cobra.Command, source, dest, namingTemplate, acoustidKey, dbPath string, dryRun, move bool) error {
	tpl, err := naming.Parse(namingTemplate)
	if err != nil {
		return err
	}

	files, err := scanPathForAudio("import", source)
	if err != nil {
		return err
	}
	if len(files) == 0 {
		_, err := fmt.Fprintf(cmd.OutOrStdout(), "no audio files found under %s\n", source)
		return err
	}

	// dry-run touches nothing, including the library database — only open
	// it once there's actually something to record.
	var db *library.DB
	if !dryRun {
		db, err = openLibrary(dbPath)
		if err != nil {
			return err
		}
		defer func() { _ = db.Close() }()
	}

	resolver := newResolver(acoustidKey)
	ctx := cmd.Context()
	out, errOut := cmd.OutOrStdout(), cmd.ErrOrStderr()
	for _, file := range files {
		track, proposal, ok := resolveFile(cmd, ctx, resolver, file)
		if !ok {
			continue
		}
		if err := printProposal(cmd, file, track, proposal); err != nil {
			return err
		}

		destPath := filepath.Join(dest, tpl.Render(destinationFields(track, proposal, file)))
		if _, err := fmt.Fprintf(out, "  -> %s\n\n", destPath); err != nil {
			return err
		}
		if dryRun {
			continue
		}

		if _, err := os.Stat(destPath); err == nil {
			_, _ = fmt.Fprintf(errOut, "warning: %s: destination already exists, skipping\n", destPath)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
			_, _ = fmt.Fprintf(errOut, "warning: %s: %v\n", file, err)
			continue
		}

		// Write tags to the source file first, so the copy/move carries the
		// resolved metadata rather than the file's original tags.
		if err := audio.WriteTags(file, writableTagsFromProposal(proposal)); err != nil {
			_, _ = fmt.Fprintf(errOut, "warning: %v\n", err)
			continue
		}

		if move {
			err = os.Rename(file, destPath)
		} else {
			err = copyFile(file, destPath)
		}
		if err != nil {
			_, _ = fmt.Fprintf(errOut, "warning: %s: %v\n", file, err)
			continue
		}
		if _, err := fmt.Fprintf(out, "  imported to %s\n\n", destPath); err != nil {
			return err
		}

		// Read the file back from its final location, so the database
		// records exactly what's there rather than a hand-merged guess.
		final, err := audio.ReadTrack(destPath)
		if err != nil {
			_, _ = fmt.Fprintf(errOut, "warning: %s: %v\n", destPath, err)
			continue
		}
		if err := db.Upsert(final); err != nil {
			_, _ = fmt.Fprintf(errOut, "warning: %s: failed to update library database: %v\n", destPath, err)
		}
	}
	return nil
}

// destinationFields merges a track's current tags with its resolved
// proposal (proposal fields win where offered) and the file's own
// container/format facts, into the naming.Fields the template renders
// from.
func destinationFields(track audio.Track, proposal *resolve.Proposal, file string) naming.Fields {
	var pTitle, pArtist, pAlbum, pAlbumArtist string
	var pYear int
	if proposal != nil {
		pTitle, pArtist, pAlbum, pAlbumArtist, pYear = proposal.Title, proposal.Artist, proposal.Album, proposal.AlbumArtist, proposal.Year
	}

	year := track.Year
	if pYear != 0 {
		year = pYear
	}

	return naming.Fields{
		Artist:       fieldOrCurrent(pArtist, track.Artist),
		AlbumArtist:  fieldOrCurrent(pAlbumArtist, track.AlbumArtist),
		Album:        fieldOrCurrent(pAlbum, track.Album),
		Title:        fieldOrCurrent(pTitle, track.Title),
		Format:       string(track.FileType),
		Ext:          strings.TrimPrefix(strings.ToLower(filepath.Ext(file)), "."),
		BitrateClass: bitrateClass(string(track.FileType)),
		Year:         year,
		Disc:         track.DiscNum,
		Track:        track.TrackNum,
	}
}

func fieldOrCurrent(proposed, current string) string {
	if proposed != "" {
		return proposed
	}
	return current
}

// bitrateClass classifies a container format as "lossless" or "lossy" for
// the {bitrate_class} naming variable. This is a container-level heuristic,
// not a real codec inspection (an M4A could in principle hold ALAC, which
// dhowden/tag doesn't currently distinguish from AAC) — good enough for
// naming; Milestone 7's transcode presets need, and will do, better.
func bitrateClass(fileType string) string {
	switch fileType {
	case "FLAC", "DSF", "ALAC":
		return "lossless"
	default:
		return "lossy"
	}
}
